services:
  web:
    build: .
    container_name: web_app
    command: gunicorn project.wsgi:application --bind 0.0.0.0:14030
    ports:
      - "14030:14030"
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=project.settings

  worker:
    build: .
    container_name: celery_worker
    command: celery -A project worker --loglevel=info
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=project.settings

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6373:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
